### ISSUE TITLE
Support URL query

### ISSUE THREAD

**Issue by fulldecent** [0xcert/erc721-validator#9]
We would like a specific URL, including a query string, to correspond to a specific scan.

This project is really great and we should expect that people are going to want to directly link to test results.

# Work plan

- [ ] When starting a scan use Javascript History API to change URL to https://erc721validator.org?address=XXXX&network=mainnet
- [ ] Update link from CryptoKitties: 0x06... to go to https://erc721validator.org?address=XXXX

# Follow on work

- [ ] Generate a list of tests we have performed and give the links to #marketing

**Comment by MoMannn** [comment]
This issue was opened on the wrong repo. So I opened it on the gui repo: https://github.com/0xcert/erc721-validator-ui/issues/1
and I am closing this.
